### ISSUE TITLE
Implementation of hit objects

### ISSUE THREAD

**Issue by GSculerlor** [GSculerlor/Cytosu#2]
Open it as an epic issue to track hit objects implementation

- [ ] Basic/tap note (hit circle)
- [ ] Hold note (sliders and spinner)
- [ ] Flick note (still not sure whether I want to implement this note)

It also includes both hit object and drawable hit object implementation
